In [5]:
#Задача 1
def share_bread(N, K):
    # your code here
    x = K//N
    y = K%N
    return x, y

# если в функции всё верно, то после выполнения этой строчки, не должно выскакивать ошибок
assert share_bread(N=3, K=14) == (4, 2)

In [38]:
#Задача 2
#если его номер кратен 4, но не кратен 100, а также если он кратен 400
def leap_year(year):
    # your code here
    text_result = 'YOU SHALL NOT PASS'
    if year % 100 == 0:
        if year%400 == 0: text_result = 'YOU SHALL PASS'
    elif year % 4 == 0: text_result = 'YOU SHALL PASS'
    return text_result

assert leap_year(5) == 'YOU SHALL NOT PASS'

YOU SHALL NOT PASS


In [46]:
#Задача 3
from math import sqrt
def amulet_area(a, b, c):
    # your code here
    p = (a+b+c)/2
    S = sqrt(p*(p-a)*(p-b)*(p-c))
    return S

assert amulet_area(3, 4, 5) == 6

In [9]:
#Задача 4
import numpy as np
from numpy import dot
from numpy.linalg import norm

def cal_euclidean(a, b):
    distance = np.sqrt(np.sum(np.square(a-b)))
    return distance

def cal_manhattan(a, b):    
    ## Your code here
    distance = np.sum(np.abs(a-b))
    return distance

def cal_cosine(a, b):    
    distance = dot(a, b)/(norm(a)*norm(b))
    return distance

a = np.random.randint(-10, 10, size=10)
b = np.random.randint(-10, 10, size=10)
print(cal_euclidean(a, b))
print(cal_manhattan(a, b))
print(cal_cosine(a, b))
#расчет по формуле из википедии, ссылка в следующем окне
print(np.linalg.norm(a-b,ord=1)) #расстояние манхэттена проверка
print(np.dot(a,b)/(np.linalg.norm(a)*(np.linalg.norm(b))))  #косинусное расстояние проверка

13.92838827718412
42
0.3941273728776353
42.0
0.3941273728776353


In [63]:
#https://translated.turbopages.org/proxy_u/en-ru.ru.df3d10b6-61d9455c-2361e964-74722d776562/https/en.wikipedia.org/wiki/Cosine_distance

In [17]:
#Задача 5
import numpy as np

my_array = np.random.rand(100) #Данная функция создает массив указанной формы 
#и заполняет его случайными числами с плавающей точкой, которые равномерно распределены в интервале [0, 1)
my_array[np.argmax(my_array)] = 1
my_array[np.argmin(my_array)] = 0
print(np.max(my_array), np.min(my_array))
print(my_array)

1.0 0.0
[0.86524292 0.92040903 0.39413437 0.9211428  0.06012251 0.23298383
 0.18164576 0.35324713 0.10692154 0.49426293 0.5034617  0.92819728
 0.61356302 0.14285619 0.63757879 0.61586881 0.55074567 0.43423638
 0.03544282 0.53593359 0.88690541 0.93107109 0.0534636  0.93486671
 0.91635468 0.78830534 0.52106875 0.83840091 0.06024105 0.21810762
 0.2488857  0.22646208 0.6010938  0.94154456 0.47334222 0.46355142
 0.37265398 0.67033744 0.37478011 0.88322643 0.44922121 0.71169428
 0.07461076 0.59293358 0.         0.89436072 0.27172513 0.38926535
 0.22684926 0.1165817  0.79850443 0.92033114 0.6007111  0.37512154
 0.22474634 0.39805334 0.61587851 0.29471181 0.5484499  0.36731132
 0.79068527 0.94654867 0.60401648 0.78088984 0.48564707 0.02299286
 0.43687936 0.35461536 0.26057741 0.83991246 0.02971814 0.03824927
 0.2268725  0.4358327  0.82690759 0.63466647 0.07379441 0.4265878
 0.41351643 0.19946665 0.19456648 0.15228939 0.51842167 0.81327133
 0.42418995 0.44422922 0.85853286 0.3209548  1.        

In [23]:
import numpy as np
my_array = np.random.randint(0, 50, (5, 6)) ## Your code here
max = np.max(my_array)
selected_column = np.empty((5,1))
for i in range(6):
    for j in range(5):
        if my_array[j,i] == max:
            selected_column = my_array[:,i]

print('Shape: ',my_array.shape)
print('Array')
print(my_array)
print(selected_column)

Shape:  (5, 6)
Array
[[25 15 37 34 26 16]
 [45 16  7 18 46 38]
 [49  4 45  6 33 42]
 [42 22 16 46 27 22]
 [24  5 31 23 14 47]]
[25 45 49 42 24]


In [111]:
import numpy as np
def get_unique_rows(X):
    shape = X.shape #последовательность  
    X_unique = np.unique(X, axis=0)                  
    return X_unique
X = np.random.randint(4, 6, size=(10,3))
print(X)


print(get_unique_rows(X))

[[4 4 4]
 [5 4 5]
 [4 4 4]
 [4 5 5]
 [5 4 4]
 [5 5 4]
 [4 4 5]
 [5 4 5]
 [4 4 5]
 [5 4 4]]
[[4 4 4]
 [4 4 5]
 [4 5 5]
 [5 4 4]
 [5 4 5]
 [5 5 4]]
