In [5]:
#Задача 1
def share_bread(N, K):
    # your code here
    x = K//N
    y = K%N
    return x, y

# если в функции всё верно, то после выполнения этой строчки, не должно выскакивать ошибок
assert share_bread(N=3, K=14) == (4, 2)

In [38]:
#Задача 2
#если его номер кратен 4, но не кратен 100, а также если он кратен 400
def leap_year(year):
    # your code here
    text_result = 'YOU SHALL NOT PASS'
    if year % 100 == 0:
        if year%400 == 0: text_result = 'YOU SHALL PASS'
    elif year % 4 == 0: text_result = 'YOU SHALL PASS'
    return text_result

assert leap_year(5) == 'YOU SHALL NOT PASS'

YOU SHALL NOT PASS


In [46]:
#Задача 3
from math import sqrt
def amulet_area(a, b, c):
    # your code here
    p = (a+b+c)/2
    S = sqrt(p*(p-a)*(p-b)*(p-c))
    return S

assert amulet_area(3, 4, 5) == 6

In [102]:
#Задача 4
import numpy
from numpy import dot
from numpy.linalg import norm

def cal_euclidean(a, b):
    ## Your code here
    summ = np.zeros_like(a)
    
    for i in range(len(a)):
        summ[i] = a[i]+b[i]
    summ = np.square(summ)
    summ = summ.sum()
    distance = np.sqrt(summ)
    return distance

def cal_manhattan(a, b):    
    ## Your code here
    diff = np.zeros_like(a)
    
    for i in range(len(a)):
        diff[i] = a[i]-b[i]
        diff = np.absolute(diff)
        distance = diff.sum()
    return distance

def cal_cosine(a, b):    
    ## Your code here
    summ = dot(a,b)
    a = np.square(a)
    a = a.sum()
    a = np.sqrt(a)
    b = np.square(b)
    b = b.sum()
    b = np.sqrt(b) 
    distance =  1 - np.absolute(summ/(a*b)) #рассчитано по формуле из задания, 
    #только проставила модуль, т.к. если подмодульное выражение отрицательное, то получается значение больше единицы, что неверно
            
    return distance

a = np.random.randint(-10, 10, size=10)
b = np.random.randint(-10, 10, size=10)
print(cal_euclidean(a, b))
print(cal_manhattan(a, b))
print(cal_cosine(a, b))
print(dot(a, b)/(norm(a)*norm(b))) #расчет по формуле из википедии, ссылка в следующем окне


25.69046515733026
68
0.9388865297643383
0.06111347023566175


In [63]:
#https://translated.turbopages.org/proxy_u/en-ru.ru.df3d10b6-61d9455c-2361e964-74722d776562/https/en.wikipedia.org/wiki/Cosine_distance

In [24]:
#Задача 5
import numpy as np

my_array = np.random.rand(100) #Данная функция создает массив указанной формы 
#и заполняет его случайными числами с плавающей точкой, которые равномерно распределены в интервале [0, 1), его не надо видоизменять
print(np.max(my_array), np.min(my_array))
print(my_array)

0.983251808385949 0.0025710369311526815
[0.63731243 0.03862375 0.70445364 0.12540164 0.45533749 0.68483543
 0.9646775  0.33216231 0.65714907 0.23454881 0.45615115 0.58065974
 0.67660067 0.09933144 0.5023018  0.23266424 0.57595545 0.03491975
 0.14860127 0.00257104 0.60921494 0.43110764 0.58254285 0.46294589
 0.93210997 0.15782431 0.69941668 0.0815313  0.67689065 0.24586522
 0.60557902 0.98027888 0.9315292  0.98325181 0.93495807 0.09470608
 0.50858474 0.51769461 0.69742333 0.6491904  0.59841479 0.35330089
 0.68624645 0.69826113 0.52257961 0.31438827 0.57484462 0.38401905
 0.79565516 0.63778734 0.54617147 0.80054286 0.8575889  0.41849348
 0.61177647 0.64483934 0.71968862 0.53389119 0.09028022 0.7536562
 0.54502717 0.46053981 0.45661129 0.02195983 0.739094   0.47795461
 0.36027741 0.28328226 0.46914479 0.70269788 0.68803972 0.62770207
 0.63156698 0.28289724 0.52754301 0.36398117 0.28018392 0.42500007
 0.86148326 0.23015538 0.56556841 0.85858093 0.93375566 0.40974049
 0.25544915 0.89958054 

In [37]:
import numpy as np
my_array = np.random.randint(0, 50, (5, 6)) ## Your code here
max = np.max(my_array)
selected_column = np.empty((5,1))
for i in range(6):
    for j in range(5):
        if my_array[j,i] == max:
            selected_column = my_array[:,i]

print('Shape: ',my_array.shape)
print('Array')
print(my_array)
print(selected_column)

Shape:  (5, 6)
Array
[[32  0 20 10 19  5]
 [ 3  2 25  5 16 10]
 [40 16 23  3 21 27]
 [25 17 40 12 43 28]
 [43  9 13 47 32 31]]
[10  5  3 12 47]


In [111]:
import numpy as np
def get_unique_rows(X):
    shape = X.shape #последовательность  
    X_unique = np.unique(X, axis=0)                  
    return X_unique
X = np.random.randint(4, 6, size=(10,3))
print(X)


print(get_unique_rows(X))

[[4 4 4]
 [5 4 5]
 [4 4 4]
 [4 5 5]
 [5 4 4]
 [5 5 4]
 [4 4 5]
 [5 4 5]
 [4 4 5]
 [5 4 4]]
[[4 4 4]
 [4 4 5]
 [4 5 5]
 [5 4 4]
 [5 4 5]
 [5 5 4]]
